// <auto-generated />
namespace DocitcareWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updated_UserTable_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_UserTable_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202104062035061_updated_UserTable_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
