// <auto-generated />
namespace DocitcareWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_new_column_Registration_UserTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_new_column_Registration_UserTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104192018185_Added_new_column_Registration_UserTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
