// <auto-generated />
namespace DocitcareWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleting_BranchId_in_Department1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleting_BranchId_in_Department1));
        
        string IMigrationMetadata.Id
        {
            get { return "202103261953070_deleting_BranchId_in_Department1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
