// <auto-generated />
namespace DocitcareWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Deleted_row_User_Details_departmentid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deleted_row_User_Details_departmentid));
        
        string IMigrationMetadata.Id
        {
            get { return "202104070913040_Deleted_row_User_Details_departmentid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
