// <auto-generated />
namespace DocitcareWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addded_departmentid_userdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addded_departmentid_userdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202104070914266_addded_departmentid_userdetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
