// <auto-generated />
namespace DocitcareWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class created_DepartmentBranches_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_DepartmentBranches_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202103302120214_created_DepartmentBranches_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
